# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{websolr-rails}
  s.version = "2.4.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Kyle Maxwell"]
  s.date = %q{2010-01-06}
  s.default_executable = %q{websolr}
  s.description = %q{Makes Sunspot and acts_as_solr play with WebSolr}
  s.email = %q{kyle@kylemaxwell.com}
  s.executables = ["websolr"]
  s.extra_rdoc_files = [
    "LICENSE",
     "README.rdoc"
  ]
  s.files = [
    ".document",
     ".gitignore",
     "CHANGELOG",
     "LICENSE",
     "README.rdoc",
     "Rakefile",
     "VERSION",
     "bin/websolr",
     "lib/plain_option_parser.rb",
     "lib/websolr-rails.rb",
     "lib/websolr.rb",
     "spec/plain_option_parser_spec.rb",
     "spec/spec_helper.rb",
     "websolr-rails.gemspec"
  ]
  s.homepage = %q{http://github.com/onemorecloud/websolr-rails}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.5}
  s.summary = %q{WebSolr adapter}
  s.test_files = [
    "spec/plain_option_parser_spec.rb",
     "spec/spec_helper.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
    else
    end
  else
  end
end

